version: '3'

volumes:
  
  server_vol:
    driver_opts:
      type: none
      device: $PWD/server
      o: bind

services:

  angular:
    build: client
    command: nodemon angular-client
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - "express"
    ports:
      - "4200:4200"
      - "49153:49153"

  express:
    build: server 
    # nodemon should watch the dist directory
    command: nodemon ./dist/server.js -w dist/
    volumes:
      - server_vol:/app
    depends_on:
      - "transpiler"
    ports:
      - "3000:3000"
    links:
      - primary

  primary:
    image: mongo:4.1.1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    ports:
      - "27017:27017"
  
  secondary:
    image: mongo:4.1.1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    ports:
      - "27018:27017"
  
  mongoreplica:
    image: mongo:4.1.1
    volumes:
      - ./scripts:/scripts
    restart: always
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]

  transpiler:
    build: server
    volumes:
      - server_vol:/app
    # typescript should watch the src directory
    command: tsc -w -p .