version: '3'

services:
  angular:
    build: client
    command: nodemon angular-client
    volumes:
      - ./client:/app
    ports:
      - "4200:4200"
      - "49153:49153"

  express:
    build: server
    command: nodemon server.js
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"